name: Build, Push, Deploy
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_uri: ${{ steps.set_image.outputs.image_uri }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push
        id: build
        run: |
          REPO="${{ steps.ecr.outputs.registry }}/${{ github.repository_owner }}/go-app"
          IMAGE="${REPO}:${{ github.sha }}"
          docker build -t "$IMAGE" ./app
          docker push "$IMAGE"
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
      - name: Set output
        id: set_image
        run: echo "::set-output name=image_uri::${{ steps.build.outputs.image }}"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      - name: Terraform init
        working-directory: infra
        env:
          TF_IN_AUTOMATION: true
        run: terraform init -input=false -upgrade
      - name: Terraform apply
        working-directory: infra
        env:
          TF_VAR_app_image: ${{ needs.build.outputs.image_uri }}
          TF_VAR_tf_state_bucket: ${{ secrets.TF_STATE_BUCKET }}
          TF_VAR_tf_dynamodb_table: ${{ secrets.TF_DYNAMODB_TABLE }}
          AWS_REGION: ap-southeast-2
        run: terraform apply -auto-approve -input=false
